# Generated by Django 2.2.12 on 2020-05-26 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwitter', '0021_auto_20200510_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='DweetNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('li', 'like'), ('co', 'comment'), ('re', 'remix')], max_length=2)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('dweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwitter.Dweet')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
