# Generated by Django 2.2.12 on 2020-06-05 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0022_dweetnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dweet',
            name='posted',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dweetnotification',
            name='verb',
            field=models.CharField(choices=[('li', 'like'), ('co', 'comment'), ('re', 'remix')], max_length=8),
        ),
    ]
